import time
from pages.Workorders.AWO.create_workorder import CreateAWO
from tests.conftest import setup
from tests.test_login import test_login
from utils.module_data_reader import get_testcase_data
def test_create_work_order(test_login):
    create_awo = CreateAWO(test_login)
    testdata = get_testcase_data('AWO',"TC_AW001")
    priority = testdata.get('Priority')
    category = testdata.get('Category')
    sub_category = testdata.get('Sub Category')
    description = testdata.get('Problem Description')
    name = testdata.get('Name')
    number = testdata.get('Number')
    selection = testdata.get('Selection')
    system_user = testdata.get('System User')
    property = testdata.get('Properties')
    tenant = testdata.get('Company Name (Tenants)')
    location_A = testdata.get('Level A')
    location_B = testdata.get('Level B')
    location_C = testdata.get('Level C')
    global_name = testdata.get('Global_Name')
    global_number = testdata.get('Global_Number')

    time.sleep(5)
    create_awo.click_Apps()
    create_awo.Module('Work Orders')
    create_awo.Sub_Module('Airfield Work Orders')
    time.sleep(10)
    create_awo.Last_work_order_id()
    create_awo.New_Work_Order()
    create_awo.Priority(priority)
    create_awo.Category(category)
    create_awo.Sub_category(sub_category)
    create_awo.Location_pointer()
    create_awo.Pointer_on_map()
    create_awo.Description(description)
    time.sleep(10)
    create_awo.Custom_fields('Name',name)
    create_awo.Custom_fields('Number',number)
    create_awo.Check_box()
    create_awo.Selection(selection)
    create_awo.dynamic_dropdown('System User')
    create_awo.section_value(system_user)
    create_awo.Date_and_Time('Date Time')
    create_awo.switch_month_to_year('Date Time')
    create_awo.switch_month_to_year('Date Time')
    create_awo.select_month_and_year('2025')
    create_awo.select_month_and_year('May')
    create_awo.select_date('Date Time',25)
    create_awo.dynamic_dropdown('Properties')
    create_awo.section_value(property)
    create_awo.dynamic_dropdown('Company Name (Tenants)')
    create_awo.section_value(tenant)
    create_awo.Global_location('Level A')
    create_awo.Global_location_value(location_A)
    create_awo.Global_location('Level B')
    create_awo.Global_location_value(location_B)
    create_awo.Global_location('Level C')
    create_awo.Global_location_value(location_C)
    create_awo.Global_custom_fields('Name',global_name)
    create_awo.Global_custom_fields('Number',global_number)
    create_awo.Date_and_Time('Date and Time')
    create_awo.switch_month_to_year('Date and Time')
    create_awo.switch_month_to_year('Date and Time')
    create_awo.select_month_and_year('2025')
    create_awo.select_month_and_year('Aug')
    create_awo.select_date('Date and Time',20)
    create_awo.multi_select('20')
    create_awo.Create()
    time.sleep(8)
    create_awo.back_to_work_orders()
    time.sleep(8)
    create_awo.Last_work_order_id()
    time.sleep(10)
